### ISSUE TITLE
Symbolizer editor window out of browser view when showing up 

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler#1299] opened 2020-09-28 11:08 UTC
# Bug

**Describe the bug**
When the symbolizer editor window is opened on small screens with not enough vertical space the window is rendered outside of the browser view (even tough it should be restricted to the browser's view.):

![grafik](https://user-images.githubusercontent.com/1185547/94424388-6ebe1e00-018a-11eb-8f42-a03d1ef1523b.png)

If the user drags the window a bit it snaps back, so it is completely visible.   

**To Reproduce**
1. Go to https://geostyler.github.io/geostyler-demo/
2. Resize your browser window so the vertical space is reduced to at least to 700px
3. Click the symbolizer preview to open the symbolizer editor window
4. See that the symbolizer editor window is partially placed outside the browser's view
5. Drag the window a bit (by dragging the header)
6. See that the window snaps back and is completely visible 

**Expected behavior**
The symbolizer editor window should be completely visible when it is opened.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19 64 Bit
 - Browser: Chromium 85 / Firefox 81

**Comment by marcjansen** [comment] 2020-09-28 12:56
Thanks for the report, confirmed on my side. I faintly remember (but might be wrong) that @hwbllmnn has fixed such a behaviour in a recent project of ours. He might have an idea.

**Comment by hwbllmnn** [comment] 2020-09-28 13:37
I just fixed the symbolizer window content to have scroll bars:

```
  .ant-collapse-content {
      overflow: auto;
  }
```

**Comment by chrismayer** [comment] 2020-09-28 14:54
@hwbllmnn this did not work for me.

I check what is going wrong and for my understanding dragging behaviour uses the CSS `translate` function to re-position the window element due to dragging.
Initially it is set to something like `transform: translate(301px, 257px)` on the DOM element itself, which does not fit. It should be more like `transform: translate(50vh, calc(100vh - 472px))` whereas `472px` is the symbolizer editor window height. So maybe the defaults could be changed, like it is done here: https://github.com/geostyler/geostyler/blob/master/src/Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow.tsx#L109 ?

**Comment by hwbllmnn** [comment] 2020-09-29 05:56
Yes, probably. I actually meant to say that I didn't fix your problem but had a different one...

**Comment by chrismayer** [comment] 2020-10-06 06:25
I did some further investigations. There are two problems:

1. We inject the `boundingClientRect` of the symbolizer preview image into `SymbolizerEditorWindow`, so `y: y || window.innerHeight / 2` in the `render` function of the `SymbolizerEditorWindow` would always take the `y` value of the injected `boundingClientRect`. See [here](https://github.com/geostyler/geostyler/blob/master/src/Component/RuleTable/RuleTable.tsx#L254). By removing this another problems arises:

2. The calculation for the boundary in [react-rnd](https://www.npmjs.com/package/react-rnd) (`body` in our case) is done when dragging starts (see function [onDragStart](https://github.com/bokuweb/react-rnd/blob/master/src/index.tsx#L304)). This should be done earlier to ensure the initial position is within the boundary (not just while dragging).

**Comment by KaiVolland** [comment] 2022-12-16 08:31
The Symbolizer Window always opens snapped to the right of the symbolizer, which is intended. I guess we could disucss if a modal would be more appropriate then a window. I'll close this and add this topic to the next monthly discussion.

**Closed by KaiVolland** 2022-12-16 08:31 UTC
Labels: bug, codesprint
