### ISSUE TITLE
GeoStyler demo fails to load GeoServer "population" demo style

### ISSUE THREAD

**Issue by aaime** [geostyler/geostyler#1867] opened 2022-08-17 12:36 UTC
# Bug

**Describe the bug**
Trying to upload and parse the Geoserver population style (used in topp:states) makes the GeoStyler demo wait indefinitely, with the browser eventually suggesting to kill the process

**To Reproduce**
1. Go to https://geostyler.github.io/geostyler-demo/
2. Click on "Load style", "SLD style parser"
3. Upload the style found at https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/popshade.sld
4. The GUI never finishes loading, eventually the browser suggests killing the process

**Expected behavior**
It's a simple categorical style, should be loaded without issues

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Chrome
 - Version 104

**Comment by weskamm** [comment] 2022-08-18 06:53
Tried to reproduce this issue, but while the small loadingmask keeps rotating infinetly (which is a bug), the style itself loads quickly without errors and is displayed correctly.

Chromium wanted me to save the file as a "txt", i changed that to sld. Not sure if that may be related?

**Comment by aaime** [comment] 2022-08-18 07:21
Interesting, this morning it loaded instantly, it would not yesterday...

I've kept poking it with other styles, here are a few show various types of issues:
* https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/pophatch.sld (says "loaded successfully" and then the page turns completely white, besides the "docs npm" and "imprint" bars at the bottom)
* https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/dem.sld (loads correctly, but the UI does not give much impression that it actually happened, the rule row is all blank)
* https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/giant_polygon.sld (loads, the symbol icon is a "broken document", fill-color is gone, fill-opacity is "NaN"... the same happens with Lakes and poly_landmarks, all from the GeoServer release data directory)
*

**Comment by KaiVolland** [comment] 2022-08-18 08:48
Thanks for testing and reporting. Here is what i can say about the issues:

> * https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/pophatch.sld (says "loaded successfully" and then the page turns completely white, besides the "docs npm" and "imprint" bars at the bottom)

I could reproduce it and will investigate what is going on here. The white page is typically for buggy react code and i guess we missed some try catch stuff somewhere. 

> * https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/dem.sld (loads correctly, but the UI does not give much impression that it actually happened, the rule row is all blank)

The style was loaded correctly, but currently there is no preview for RasterSymbolizers. But if you click on the (empty) symbolizer of the first rule and then on "ColorMap" you will find what you where looking for. :slightly_smiling_face: 

> * https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/giant_polygon.sld (loads, the symbol icon is a "broken document", fill-color is gone, fill-opacity is "NaN"... the same happens with Lakes and poly_landmarks, all from the GeoServer release data directory)

This seems to be a bug in the `geostlyer-sld-parser`.

**Comment by KaiVolland** [comment] 2022-12-13 12:52
This is fixed now, as the demo uses the latest geostyler-sld-parser.

**Closed by KaiVolland** 2022-12-13 12:52 UTC
Labels: bug
